### ISSUE TITLE
Connection error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:598)

### ISSUE THREAD

**Issue by ivan** [ArchiveTeam/wpull#108]
Trying to grab https://www.nanog.org/ or https://nanog.org/ doesn't seem to work:

```
# ~/.local/bin/wpull3 --debug "https://www.nanog.org/"
DEBUG Setting pragmas.
DEBUG Loaded cookies: []
DEBUG Release in-progress.
DEBUG Get next URL todo.
DEBUG Return record URLRecord(url='https://www.nanog.org/', status='in_progress', try_count=0, level=0, top_url=None, status_code=None, referrer=None, inline=None, link_type=None, url_encoding=None, post_data=None, filename=None).
DEBUG Begin session for URLRecord(url='https://www.nanog.org/', status='in_progress', try_count=0, level=0, top_url=None, status_code=None, referrer=None, inline=None, link_type=None, url_encoding=None, post_data=None, filename=None) URLInfo(scheme='https', netloc='www.nanog.org', path='/', query=None, fragment='', username=None, password=None, hostname='www.nanog.org', port=443, raw='https://www.nanog.org/', encoding='utf-8').
INFO Fetching ‘https://www.nanog.org/’.
DEBUG Client fetch request <Request(GET, /, HTTP/1.1)>.
DEBUG Connection pool queue request <Request(GET, /, HTTP/1.1)>
DEBUG New host pool.
DEBUG Host pool running (Addr=('www.nanog.org', 443) SSL=True).
DEBUG Host pool running (Addr=('www.nanog.org', 443) SSL=True).
DEBUG Host pool running (Addr=('www.nanog.org', 443) SSL=True).
DEBUG Host pool running (Addr=('www.nanog.org', 443) SSL=True).
DEBUG Host pool running (Addr=('www.nanog.org', 443) SSL=True).
DEBUG Host pool running (Addr=('www.nanog.org', 443) SSL=True).
DEBUG Host pool running (Addr=('www.nanog.org', 443) SSL=True).
DEBUG Host pool queue request <Request(GET, /, HTTP/1.1)>
DEBUG Host pool got request <Request(GET, /, HTTP/1.1)>
DEBUG Getting a connection.
DEBUG Making another connection.
DEBUG Reading PEM /home/at/.local/lib/python3.4/site-packages/wpull/cert/ca-bundle.pem.
DEBUG Reading PEM /etc/ssl/certs/ca-certificates.crt.
DEBUG CA certs loaded.
DEBUG Request <Request(GET, /, HTTP/1.1)>.
DEBUG Lookup address www.nanog.org 443.
DEBUG Resolving www.nanog.org 443 2.
DEBUG Resolving www.nanog.org 443 10.
DEBUG Resolved addresses: [(<AddressFamily.AF_INET: 2>, ('50.31.151.73', 443)), (<AddressFamily.AF_INET6: 10>, ('2001:1838:2001:8::9', 443, 0, 0))].
DEBUG Selected (<AddressFamily.AF_INET: 2>, ('50.31.151.73', 443)) as address.
DEBUG Socket to 2/('50.31.151.73', 443).
DEBUG Connecting to ('50.31.151.73', 443).
DEBUG Fetch exception.
DEBUG Stream closing.
DEBUG Stream closed. active=True connected=False closed=True
DEBUG Host pool got an error from fetch: Connection error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:598)
DEBUG Traceback (most recent call last):
  File "/home/at/.local/lib/python3.4/site-packages/wpull/http/connection.py", line 175, in _connect
    self._resolved_address, timeout=self._params.connect_timeout
  File "/home/at/.local/lib/python3.4/site-packages/tornado/gen.py", line 520, in run
    next = self.yield_point.get_result()
  File "/home/at/.local/lib/python3.4/site-packages/tornado/gen.py", line 409, in get_result
    return self.runner.pop_result(self.key).result()
  File "/home/at/.local/lib/python3.4/site-packages/tornado/concurrent.py", line 129, in result
    raise_exc_info(self.__exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/home/at/.local/lib/python3.4/site-packages/tornado/stack_context.py", line 302, in wrapped
    ret = fn(*args, **kwargs)
  File "/home/at/.local/lib/python3.4/site-packages/tornado/gen.py", line 574, in inner
    self.set_result(key, result)
  File "/home/at/.local/lib/python3.4/site-packages/tornado/gen.py", line 500, in set_result
    self.run()
  File "/home/at/.local/lib/python3.4/site-packages/tornado/gen.py", line 529, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/at/.local/lib/python3.4/site-packages/wpull/iostream.py", line 638, in connect
    yield self._do_handshake(timeout)
  File "/home/at/.local/lib/python3.4/site-packages/tornado/gen.py", line 520, in run
    next = self.yield_point.get_result()
  File "/home/at/.local/lib/python3.4/site-packages/tornado/gen.py", line 409, in get_result
    return self.runner.pop_result(self.key).result()
  File "/home/at/.local/lib/python3.4/site-packages/tornado/concurrent.py", line 129, in result
    raise_exc_info(self.__exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/home/at/.local/lib/python3.4/site-packages/tornado/stack_context.py", line 302, in wrapped
    ret = fn(*args, **kwargs)
  File "/home/at/.local/lib/python3.4/site-packages/tornado/gen.py", line 574, in inner
    self.set_result(key, result)
  File "/home/at/.local/lib/python3.4/site-packages/tornado/gen.py", line 500, in set_result
    self.run()
  File "/home/at/.local/lib/python3.4/site-packages/tornado/gen.py", line 531, in run
    yielded = self.gen.send(next)
  File "/home/at/.local/lib/python3.4/site-packages/wpull/iostream.py", line 649, in _do_handshake
    self._socket.do_handshake()
  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:598)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/at/.local/lib/python3.4/site-packages/wpull/http/connection.py", line 634, in _process_request
    response = yield connection.fetch(request, **kwargs)
  File "/home/at/.local/lib/python3.4/site-packages/tornado/gen.py", line 520, in run
    next = self.yield_point.get_result()
  File "/home/at/.local/lib/python3.4/site-packages/tornado/gen.py", line 409, in get_result
    return self.runner.pop_result(self.key).result()
  File "/home/at/.local/lib/python3.4/site-packages/tornado/concurrent.py", line 129, in result
    raise_exc_info(self.__exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/home/at/.local/lib/python3.4/site-packages/tornado/stack_context.py", line 302, in wrapped
    ret = fn(*args, **kwargs)
  File "/home/at/.local/lib/python3.4/site-packages/tornado/gen.py", line 574, in inner
    self.set_result(key, result)
  File "/home/at/.local/lib/python3.4/site-packages/tornado/gen.py", line 500, in set_result
    self.run()
  File "/home/at/.local/lib/python3.4/site-packages/tornado/gen.py", line 529, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/at/.local/lib/python3.4/site-packages/wpull/http/connection.py", line 220, in fetch
    response_factory)
  File "/home/at/.local/lib/python3.4/site-packages/tornado/gen.py", line 520, in run
    next = self.yield_point.get_result()
  File "/home/at/.local/lib/python3.4/site-packages/tornado/gen.py", line 409, in get_result
    return self.runner.pop_result(self.key).result()
  File "/home/at/.local/lib/python3.4/site-packages/tornado/concurrent.py", line 129, in result
    raise_exc_info(self.__exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/home/at/.local/lib/python3.4/site-packages/tornado/stack_context.py", line 302, in wrapped
    ret = fn(*args, **kwargs)
  File "/home/at/.local/lib/python3.4/site-packages/tornado/gen.py", line 574, in inner
    self.set_result(key, result)
  File "/home/at/.local/lib/python3.4/site-packages/tornado/gen.py", line 500, in set_result
    self.run()
  File "/home/at/.local/lib/python3.4/site-packages/tornado/gen.py", line 529, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/at/.local/lib/python3.4/site-packages/wpull/http/connection.py", line 249, in _process_request
    yield self._connect()
  File "/home/at/.local/lib/python3.4/site-packages/tornado/gen.py", line 520, in run
    next = self.yield_point.get_result()
  File "/home/at/.local/lib/python3.4/site-packages/tornado/gen.py", line 409, in get_result
    return self.runner.pop_result(self.key).result()
  File "/home/at/.local/lib/python3.4/site-packages/tornado/concurrent.py", line 129, in result
    raise_exc_info(self.__exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/home/at/.local/lib/python3.4/site-packages/tornado/stack_context.py", line 302, in wrapped
    ret = fn(*args, **kwargs)
  File "/home/at/.local/lib/python3.4/site-packages/tornado/gen.py", line 574, in inner
    self.set_result(key, result)
  File "/home/at/.local/lib/python3.4/site-packages/tornado/gen.py", line 500, in set_result
    self.run()
  File "/home/at/.local/lib/python3.4/site-packages/tornado/gen.py", line 529, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/at/.local/lib/python3.4/site-packages/wpull/http/connection.py", line 187, in _connect
    error=error)) from error
wpull.errors.NetworkError: Connection error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:598)

DEBUG Host pool done <Request(GET, /, HTTP/1.1)>
DEBUG Host pool semaphore released.
DEBUG Host pool running (Addr=('www.nanog.org', 443) SSL=True).
ERROR Fetching ‘https://www.nanog.org/’ encountered an error: Connection error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:598)
DEBUG Marking URL https://www.nanog.org/ status error.
DEBUG Sleeping 1.0.
^CINFO Stopping once all requests complete...
INFO Interrupt again to force stopping immediately.
DEBUG Stopping. force=False
DEBUG End session for URLRecord(url='https://www.nanog.org/', status='in_progress', try_count=0, level=0, top_url=None, status_code=None, referrer=None, inline=None, link_type=None, url_encoding=None, post_data=None, filename=None) URLInfo(scheme='https', netloc='www.nanog.org', path='/', query=None, fragment='', username=None, password=None, hostname='www.nanog.org', port=443, raw='https://www.nanog.org/', encoding='utf-8').
DEBUG Stopping. force=True
INFO FINISHED.
INFO Duration: 0:00:01. Speed: -- B/s.
INFO Downloaded: 0 files, 0.0 B.
INFO Exiting with status 4.
DEBUG Client closing.
DEBUG Closing pool for ('www.nanog.org', 443).
DEBUG Closing <wpull.http.connection.Connection object at 0x7f1174793a90>.
```

(Testing on Ubuntu 14.04.)

Firefox and Chrome are okay with their certificate.

**Comment by JustAnotherArchivist** [comment]
4.5 years later, I'm unable to reproduce this. Of course, the certificate has been replaced several times since April 2014.

[This](https://transparencyreport.google.com/https/certificates/hN7Y%2FRwJJ9X5H1Tl%2Fa%2FiGBpqakRw9R3bu79%2FlgCMiMI%3D) might be the certificate that was used back then, but unfortunately there's no way to get the actual certificate as far as I can see. Do you happen to have a copy?
