### ISSUE TITLE
AttributeError: 'tuple_iterator' object has no attribute 'key'

### ISSUE THREAD

**Issue by mback2k** [ArchiveTeam/wpull#189]
From an ArchiveBot job on an unknown pipeline:

```
ERROR Fatal exception.
Traceback (most recent call last):
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/app.py", line 101, in run
    yield From(self._builder.factory['Engine']())
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/tasks.py", line 314, in _wakeup
    value = future.result()
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/futures.py", line 277, in result
    raise self._exception
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/tasks.py", line 245, in _step
    result = coro.throw(exc)
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/engine.py", line 259, in __call__
    yield From(self._run_workers())
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/tasks.py", line 314, in _wakeup
    value = future.result()
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/futures.py", line 277, in result
    raise self._exception
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/tasks.py", line 247, in _step
    result = coro.send(value)
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/engine.py", line 64, in _run_workers
    task.result()
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/futures.py", line 277, in result
    raise self._exception
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/tasks.py", line 245, in _step
    result = coro.throw(exc)
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/engine.py", line 131, in _run_worker
    yield From(self._process_item(item))
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/tasks.py", line 314, in _wakeup
    value = future.result()
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/futures.py", line 277, in result
    raise self._exception
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/tasks.py", line 245, in _step
    result = coro.throw(exc)
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/engine.py", line 316, in _process_item
    yield From(self._process_url_item(url_item))
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/tasks.py", line 314, in _wakeup
    value = future.result()
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/futures.py", line 277, in result
    raise self._exception
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/tasks.py", line 245, in _step
    result = coro.throw(exc)
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/engine.py", line 338, in _process_url_item
    yield From(self._processor.process(url_item))
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/tasks.py", line 314, in _wakeup
    value = future.result()
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/futures.py", line 277, in result
    raise self._exception
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/tasks.py", line 245, in _step
    result = coro.throw(exc)
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/processor/web.py", line 147, in process
    @trollius.coroutine
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/tasks.py", line 314, in _wakeup
    value = future.result()
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/futures.py", line 277, in result
    raise self._exception
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/tasks.py", line 245, in _step
    result = coro.throw(exc)
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/processor/web.py", line 233, in process
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/tasks.py", line 314, in _wakeup
    value = future.result()
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/futures.py", line 277, in result
    raise self._exception
  File "/home/archivebot/.local/lib/python3.4/site-packages/trollius/tasks.py", line 247, in _step
    result = coro.send(value)
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/processor/web.py", line 282, in _process_one
    reason=response.reason,
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/processor/web.py", line 440, in _handle_response
    '''Process the response.'''
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/hook.py", line 116, in call_hook
    return self.callback_hooks[name](*args, **kwargs)
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/hook.py", line 578, in _handle_response
    response_info_dict = self.to_script_native_type(response.to_dict())
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/http/request.py", line 222, in to_dict
    'fields': list(self.fields.get_all()),
  File "/home/archivebot/.local/lib/python3.4/site-packages/wpull/namevalue.py", line 93, in get_all
    for name, values in self._map.items():
  File "/usr/lib/python3.4/_collections_abc.py", line 484, in __iter__
    for key in self._mapping:
  File "/usr/lib/python3.4/collections/__init__.py", line 89, in __iter__
    yield curr.key
AttributeError: 'tuple_iterator' object has no attribute 'key'
```

**Comment by ivan** [comment]
This happened on the ovhca1 pipeline for the `united.tm-exchange.com` job, `66exx83x8p0nkli3td0n8tkjw`
