### ISSUE TITLE
Python 3.5: RuntimeError: generator raised StopIteration

### ISSUE THREAD

**Issue by ivan** [ArchiveTeam/wpull#290]
If #287 and #289 are fixed and [some offending lines are commented out in trollius](https://github.com/ludios/trollius/commit/f757a29815c2c9f5c3a691135ff758649fe84098), then wpull crashes with:

```
$ ~/.local/bin/wpull3 https://www.google.com/
ERROR Producer died.
ERROR Fatal exception.
Traceback (most recent call last):
  File "/home/at/.local/lib/python3.5/site-packages/trollius/tasks.py", line 475, in _wait
    raise Return(done, pending)
StopIteration: ({<Task finished coro=<BaseEngine._run_worker() done, defined at /home/at/.local/lib/python3.5/site-packages/wpull/engine.py:127> exception=RuntimeError('generator raised StopIteration',)>}, set())

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/at/.local/lib/python3.5/site-packages/wpull/app.py", line 128, in run
    yield From(self._builder.factory['Engine']())
  File "/home/at/.local/lib/python3.5/site-packages/trollius/tasks.py", line 250, in _step
    result = coro.throw(exc)
  File "/home/at/.local/lib/python3.5/site-packages/wpull/engine.py", line 278, in __call__
    yield From(self._run_workers())
  File "/home/at/.local/lib/python3.5/site-packages/trollius/tasks.py", line 250, in _step
    result = coro.throw(exc)
  File "/home/at/.local/lib/python3.5/site-packages/wpull/engine.py", line 64, in _run_workers
    done_tasks = (yield From(wait_coroutine))[0]
  File "/home/at/.local/lib/python3.5/site-packages/trollius/tasks.py", line 250, in _step
    result = coro.throw(exc)
  File "/home/at/.local/lib/python3.5/site-packages/trollius/tasks.py", line 379, in wait
    result = yield From(_wait(fs, timeout, return_when, loop))
  File "/home/at/.local/lib/python3.5/site-packages/trollius/tasks.py", line 252, in _step
    result = coro.send(value)
RuntimeError: generator raised StopIteration
CRITICAL Sorry, Wpull unexpectedly crashed.
CRITICAL Please report this problem to the authors at Wpull's issue tracker so it may be fixed. If you know how to program, maybe help us fix it? Thank you for helping us help you help us all.
INFO FINISHED.
INFO Duration: 0:00:00. Speed: -- B/s.
INFO Downloaded: 0 files, 0.0 B.
INFO Exiting with status 1.
Traceback (most recent call last):
  File "/home/at/.local/lib/python3.5/site-packages/wpull/app.py", line 175, in run
    raise Return(self._exit_code)
StopIteration: 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/at/.local/bin/wpull3", line 3, in <module>
    wpull.__main__.main()
  File "/home/at/.local/lib/python3.5/site-packages/wpull/__main__.py", line 40, in main
    exit_code = application.run_sync()
  File "/home/at/.local/lib/python3.5/site-packages/wpull/app.py", line 118, in run_sync
    return self._event_loop.run_until_complete(self.run())
  File "/home/at/.local/lib/python3.5/site-packages/trollius/base_events.py", line 350, in run_until_complete
    return future.result()
  File "/home/at/.local/lib/python3.5/site-packages/trollius/futures.py", line 286, in result
    raise self._exception
  File "/home/at/.local/lib/python3.5/site-packages/trollius/tasks.py", line 252, in _step
    result = coro.send(value)
RuntimeError: generator raised StopIteration
Exception ignored in: <bound method BaseEventLoop.__del__ of <_UnixSelectorEventLoop running=False closed=True debug=False>>
Traceback (most recent call last):
  File "/home/at/.local/lib/python3.5/site-packages/trollius/base_events.py", line 395, in __del__
  File "/home/at/.local/lib/python3.5/site-packages/trollius/unix_events.py", line 65, in close
  File "/home/at/.local/lib/python3.5/site-packages/trollius/unix_events.py", line 166, in remove_signal_handler
  File "/usr/lib/python3.5/signal.py", line 47, in signal
TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object
Task exception was never retrieved
future: <Task finished coro=<BaseEngine._run_producer_wrapper() done, defined at /home/at/.local/lib/python3.5/site-packages/wpull/engine.py:91> exception=RuntimeError('generator raised StopIteration',)>
Traceback (most recent call last):
  File "/home/at/.local/lib/python3.5/site-packages/trollius/coroutines.py", line 332, in coro
    raise Return(res)
StopIteration: URLRecord(url='https://www.google.com/', status='in_progress', try_count=0, level=0, top_url=None, status_code=None, referrer=None, inline=None, link_type=None, post_data=None, filename=None)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/at/.local/lib/python3.5/site-packages/trollius/tasks.py", line 250, in _step
    result = coro.throw(exc)
  File "/home/at/.local/lib/python3.5/site-packages/wpull/engine.py", line 95, in _run_producer_wrapper
    yield From(self._run_producer())
  File "/home/at/.local/lib/python3.5/site-packages/trollius/tasks.py", line 250, in _step
    result = coro.throw(exc)
  File "/home/at/.local/lib/python3.5/site-packages/wpull/engine.py", line 111, in _run_producer
    item = yield From(self._get_item())
  File "/home/at/.local/lib/python3.5/site-packages/trollius/tasks.py", line 252, in _step
    result = coro.send(value)
RuntimeError: generator raised StopIteration
Task exception was never retrieved
future: <Task finished coro=<BaseEngine._run_worker() done, defined at /home/at/.local/lib/python3.5/site-packages/wpull/engine.py:127> exception=RuntimeError('generator raised StopIteration',)>
Traceback (most recent call last):
  File "/home/at/.local/lib/python3.5/site-packages/trollius/queues.py", line 207, in get
    raise Return(result)
StopIteration: (0, <object object at 0x7f8ce526a270>)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/at/.local/lib/python3.5/site-packages/trollius/tasks.py", line 250, in _step
    result = coro.throw(exc)
  File "/home/at/.local/lib/python3.5/site-packages/wpull/engine.py", line 136, in _run_worker
    priority, item = yield From(self._item_queue.get())
  File "/home/at/.local/lib/python3.5/site-packages/trollius/tasks.py", line 252, in _step
    result = coro.send(value)
RuntimeError: generator raised StopIteration
```

This could be related to https://docs.python.org/3/whatsnew/3.5.html#pep-479-change-stopiteration-handling-inside-generators, though that behavior is supposed to be behind a `__future__` import?

**Comment by chfoo** [comment]
It seems like RuntimeError is converted regardless of the `__future__` import. If it does that, it doesn't seem Trollius will work at all.

The code I was testing out:
```python
#from __future__ import generator_stop

#import trollius as asyncio
import asyncio

@asyncio.coroutine
#def hello_world():
async def hello_world():
    print("Hello World!")
    raise StopIteration()

loop = asyncio.get_event_loop()
loop.run_until_complete(hello_world())
loop.close()
```

**Comment by d235j** [comment]
Really strange — that sounds like a bug... maybe would be worth asking on the Python mailing list?
It seems like moving to asyncio resolves this issue; I was able to build from the ```topic/modernize_2016``` branch and run successfully (after reverting df513bf803d81cd161393c37a093b8fcf5ea0fbc). Additionally, that branch still works with Python 3.3 if the asyncio module is installed, so once PyPy updates to 3.3 (which is in progress) it would work again, unless additional changes are made that break Python 3.3.

**Comment by JustAnotherArchivist** [comment]
Closing this legacy version 1.x bug. 2.0 and up work fine on Python 3.5. The Trollius bug, if still relevant, should probably be brought up elsewhere.
