### ISSUE TITLE
wpull 2.0 crawls always finish with RuntimeError

### ISSUE THREAD

**Issue by ivan** [ArchiveTeam/wpull#328]
This is on Ubuntu 16.04 with Linux 4.4.0-22-generic:

```
# python3 --version
Python 3.5.1+

# ~/.local/bin/wpull3 http://google.com/404/
INFO Fetching ‘http://google.com/404/’.
  100.0% [=========================] 1.5 KiB 0:00:00 -- B/s
INFO Fetched ‘http://google.com/404/’: 404 Not Found. Length: 1565 [text/html; charset=UTF-8].
INFO FINISHED.
INFO Duration: 0:00:00. Speed: -- B/s.
INFO Downloaded: 0 files, 0.0 B.
Task was destroyed but it is pending!
task: <Task pending coro=<HappyEyeballsConnection._connect_dual_stack.<locals>.cleanup() running at /home/wpull2/.local/lib/python3.5/site-packages/wpull/network/pool.py:427> wait_for=<Future pending cb=[Task._wakeup()]>>
Exception ignored in: <generator object HappyEyeballsConnection._connect_dual_stack.<locals>.cleanup at 0x7f3b89f6fa98>
Traceback (most recent call last):
  File "/home/wpull2/.local/lib/python3.5/site-packages/wpull/network/pool.py", line 427, in cleanup
    conn = yield from fut
  File "/usr/lib/python3.5/asyncio/tasks.py", line 489, in _wait_for_one
    f = yield from done.get()
  File "/usr/lib/python3.5/asyncio/queues.py", line 170, in get
    getter.cancel()  # Just in case getter is not done yet.
  File "/usr/lib/python3.5/asyncio/futures.py", line 227, in cancel
    self._schedule_callbacks()
  File "/usr/lib/python3.5/asyncio/futures.py", line 242, in _schedule_callbacks
    self._loop.call_soon(callback, self)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 483, in call_soon
    handle = self._call_soon(callback, args)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 492, in _call_soon
    self._check_closed()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 320, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Task was destroyed but it is pending!
task: <Task pending coro=<HappyEyeballsConnection._connect_dual_stack.<locals>.connect_secondary() running at /home/wpull2/.local/lib/python3.5/site-packages/wpull/network/pool.py:402> wait_for=<Future pending cb=[BaseSelectorEventLoop._sock_connect_done(9)(), Task._wakeup()]> cb=[as_completed.<locals>._on_completion() at /usr/lib/python3.5/asyncio/tasks.py:479]>
```

**Comment by ivan** [comment]
Oops, not always, maybe only IPv4+IPv6 sites.

**Comment by JustAnotherArchivist** [comment]
Maybe fixed by 2778442c in #348?

**Comment by ivan** [comment]
Probably yes

**Comment by JustAnotherArchivist** [comment]
Not fixed entirely, but it only happens sometimes now. AB job em28biz2k3ouivlieq01fzfxe just had it, for example:

```
<snip>
  565484 bytes.
Settings listener connected.
/home/archivebot/.pyenv/versions/3.6.15/envs/archivebot-20230414/lib/python3.6/site-packages/wpull/protocol/http/client.py:185: UserWarning: HTTP session did not complete.
  warnings.warn(_('HTTP session did not complete.'))
Exception ignored in: <generator object BaseEventLoop._create_connection_transport at 0x7f99b82095f0>
Traceback (most recent call last):
  File "/home/archivebot/.pyenv/versions/3.6.15/lib/python3.6/asyncio/base_events.py", line 852, in _create_connection_transport
    transport.close()
  File "/home/archivebot/.pyenv/versions/3.6.15/lib/python3.6/asyncio/sslproto.py", line 325, in close
    self._ssl_protocol._start_shutdown()
  File "/home/archivebot/.pyenv/versions/3.6.15/lib/python3.6/asyncio/sslproto.py", line 557, in _start_shutdown
    self._abort()
  File "/home/archivebot/.pyenv/versions/3.6.15/lib/python3.6/asyncio/sslproto.py", line 699, in _abort
    self._transport.abort()
  File "/home/archivebot/.pyenv/versions/3.6.15/lib/python3.6/asyncio/selector_events.py", line 591, in abort
    self._force_close(None)
  File "/home/archivebot/.pyenv/versions/3.6.15/lib/python3.6/asyncio/selector_events.py", line 646, in _force_close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "/home/archivebot/.pyenv/versions/3.6.15/lib/python3.6/asyncio/base_events.py", line 595, in call_soon
    self._check_closed()
  File "/home/archivebot/.pyenv/versions/3.6.15/lib/python3.6/asyncio/base_events.py", line 381, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Task was destroyed but it is pending!
task: <Task pending coro=<HappyEyeballsConnection._connect_dual_stack.<locals>.cleanup() running at /home/archivebot/.pyenv/versions/3.6.15/envs/archivebot-20230414/lib/python3.6/site-packages/wpull/network/pool.py:427> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f99b8205e50>()]>>
Exception ignored in: <generator object HappyEyeballsConnection._connect_dual_stack.<locals>.cleanup at 0x7f99b81f6e90>
Traceback (most recent call last):
  File "/home/archivebot/.pyenv/versions/3.6.15/envs/archivebot-20230414/lib/python3.6/site-packages/wpull/network/pool.py", line 427, in cleanup
    conn = yield from fut
  File "/home/archivebot/.pyenv/versions/3.6.15/lib/python3.6/asyncio/tasks.py", line 454, in _wait_for_one
    f = yield from done.get()
  File "/home/archivebot/.pyenv/versions/3.6.15/lib/python3.6/asyncio/queues.py", line 169, in get
    getter.cancel()  # Just in case getter is not done yet.
  File "/home/archivebot/.pyenv/versions/3.6.15/lib/python3.6/asyncio/base_events.py", line 595, in call_soon
    self._check_closed()
  File "/home/archivebot/.pyenv/versions/3.6.15/lib/python3.6/asyncio/base_events.py", line 381, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Task was destroyed but it is pending!
task: <Task pending coro=<HappyEyeballsConnection._connect_dual_stack.<locals>.connect_secondary() running at /home/archivebot/.pyenv/versions/3.6.15/envs/archivebot-20230414/lib/python3.6/site-packages/wpull/network/pool.py:402> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f99b8205710>()]> cb=[as_completed.<locals>._on_completion() at /home/archivebot/.pyenv/versions/3.6.15/lib/python3.6/asyncio/tasks.py:444]>
Task was destroyed but it is pending!
task: <Task pending coro=<open_connection() running at /home/archivebot/.pyenv/versions/3.6.15/lib/python3.6/asyncio/streams.py:81> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f99bb7bb090>()]> cb=[_release_waiter(<Future pendi...9b8205710>()]>)() at /home/archivebot/.pyenv/versions/3.6.15/lib/python3.6/asyncio/tasks.py:316]>
Finished WgetDownload for Item 
<snip>
```
