### ISSUE TITLE
"No module named 'html5lib.tokenizer'"

### ISSUE THREAD

**Issue by DoomTay** [ArchiveTeam/wpull#333]
```
Graceful stopping with Unix signals is not supported on this OS.
ERROR Fatal exception.
Traceback (most recent call last):
  File "c:\users\taylor\appdata\local\programs\python\python35-32\lib\site-packages\wpull\application\app.py", line 152, in run
    yield from pipeline.process()
  File "c:\users\taylor\appdata\local\programs\python\python35-32\lib\site-packages\wpull\pipeline\pipeline.py", line 194, in process
    yield from self._process_one_worker()
  File "c:\users\taylor\appdata\local\programs\python\python35-32\lib\site-packages\wpull\pipeline\pipeline.py", line 215, in _process_one_worker
    task.result()
  File "c:\users\taylor\appdata\local\programs\python\python35-32\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "c:\users\taylor\appdata\local\programs\python\python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "c:\users\taylor\appdata\local\programs\python\python35-32\lib\site-packages\wpull\pipeline\pipeline.py", line 119, in process
    item = yield from self.process_one(_worker_id=worker_id)
  File "c:\users\taylor\appdata\local\programs\python\python35-32\lib\site-packages\wpull\pipeline\pipeline.py", line 103, in process_one
    yield from task.process(item)
  File "c:\users\taylor\appdata\local\programs\python\python35-32\lib\asyncio\coroutines.py", line 206, in coro
    res = func(*args, **kw)
  File "c:\users\taylor\appdata\local\programs\python\python35-32\lib\site-packages\wpull\application\tasks\download.py", line 31, in process
    self._build_html_parser(session)
  File "c:\users\taylor\appdata\local\programs\python\python35-32\lib\site-packages\wpull\application\tasks\download.py", line 37, in _build_html_parser
    from wpull.document.htmlparse.html5lib_ import HTMLParser
  File "c:\users\taylor\appdata\local\programs\python\python35-32\lib\site-packages\wpull\document\htmlparse\html5lib_.py", line 3, in <module>
    import html5lib.tokenizer
ImportError: No module named 'html5lib.tokenizer'
CRITICAL Sorry, Wpull unexpectedly crashed.
CRITICAL Please report this problem to the authors at Wpull's issue tracker so it may be fixed. If you know how to program, maybe help us fix it? Thank you for helping us help you help us all.
INFO Exiting with status 1.
```

This is with a fresh install of Python 3.5.2 and wpull after installing psutil

**Comment by ivan** [comment]
This is the same as #332.  You can work around it by installing `html5lib==0.9999999`.
