### ISSUE TITLE
Crash related to presence of NoneType as _transport in sslproto

### ISSUE THREAD

**Issue by falconkirtaran** [ArchiveTeam/wpull#345]
While running wpull 2.0.1 as part of archivebot, I saw this stack trace (not clear whether the first two errors are related):

```
ERROR Fetching ‘http://widgetserver.amazon.com/invalid’ encountered an error: DNS resolution failed: [Errno -2] Name or service not known
ERROR Fatal exception.
Traceback (most recent call last):
  File "/home/archivebot/.local/lib/python3.5/site-packages/wpull/application/app.py", line 152, in run
    yield from pipeline.process()
  File "/home/archivebot/.local/lib/python3.5/site-packages/wpull/pipeline/pipeline.py", line 194, in process
    yield from self._process_one_worker()
  File "/home/archivebot/.local/lib/python3.5/site-packages/wpull/pipeline/pipeline.py", line 215, in _process_one_worker
    task.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 292, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/archivebot/.local/lib/python3.5/site-packages/wpull/pipeline/pipeline.py", line 119, in process
    item = yield from self.process_one(_worker_id=worker_id)
  File "/home/archivebot/.local/lib/python3.5/site-packages/wpull/pipeline/pipeline.py", line 103, in process_one
    yield from task.process(item)
  File "/home/archivebot/.local/lib/python3.5/site-packages/wpull/application/tasks/download.py", line 492, in process
    yield from session.app_session.factory['Processor'].process(session)
  File "/home/archivebot/.local/lib/python3.5/site-packages/wpull/processor/delegate.py", line 29, in process
    return (yield from processor.process(item_session))
  File "/home/archivebot/.local/lib/python3.5/site-packages/wpull/processor/web.py", line 92, in process
    return (yield from session.process())
  File "/home/archivebot/.local/lib/python3.5/site-packages/wpull/processor/web.py", line 186, in process
    yield from self._process_loop()
  File "/home/archivebot/.local/lib/python3.5/site-packages/wpull/processor/web.py", line 245, in _process_loop
    exit_early, wait_time = yield from self._fetch_one(cast(Request, self._item_session.request))
  File "/home/archivebot/.local/lib/python3.5/site-packages/wpull/processor/web.py", line 287, in _fetch_one
    duration_timeout=self._fetch_rule.duration_timeout
  File "/home/archivebot/.local/lib/python3.5/site-packages/wpull/protocol/http/web.py", line 124, in download
    self._current_session.download(file, duration_timeout=duration_timeout)
  File "/home/archivebot/.local/lib/python3.5/site-packages/wpull/protocol/http/client.py", line 154, in download
    yield from asyncio.wait_for(read_future, timeout=duration_timeout)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 393, in wait_for
    return fut.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 292, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/archivebot/.local/lib/python3.5/site-packages/wpull/protocol/abstract/stream.py", line 17, in wrapper
    return (yield from func(self, *args, **kwargs))
  File "/home/archivebot/.local/lib/python3.5/site-packages/wpull/protocol/http/stream.py", line 202, in read_body
    yield from self._read_body_by_length(response, file)
  File "/home/archivebot/.local/lib/python3.5/site-packages/wpull/protocol/http/stream.py", line 274, in _read_body_by_length
    data = yield from self._connection.read(self._read_size)
  File "/home/archivebot/.local/lib/python3.5/site-packages/wpull/network/connection.py", line 394, in read
    data = yield from super().read(amount)
  File "/home/archivebot/.local/lib/python3.5/site-packages/wpull/network/connection.py", line 257, in read
    name='Read')
  File "/home/archivebot/.local/lib/python3.5/site-packages/wpull/network/connection.py", line 291, in run_network_operation
    data = yield from task
  File "/usr/lib/python3.5/asyncio/streams.py", line 633, in read
    self._maybe_resume_transport()
  File "/usr/lib/python3.5/asyncio/streams.py", line 402, in _maybe_resume_transport
    self._transport.resume_reading()
  File "/usr/lib/python3.5/asyncio/sslproto.py", line 351, in resume_reading
    self._ssl_protocol._transport.resume_reading()
AttributeError: 'NoneType' object has no attribute 'resume_reading'
CRITICAL Sorry, Wpull unexpectedly crashed.
CRITICAL Please report this problem to the authors at Wpull's issue tracker so it may be fixed. If you know how to program, maybe help us fix it? Thank you for helping us help you help us all.
```

**Comment by JustAnotherArchivist** [comment]
Fixed by 0c517bab in #348.
