### ISSUE TITLE
Tests for pipeline may produce bogus failures

### ISSUE THREAD

**Issue by JustAnotherArchivist** [ArchiveTeam/wpull#396]
A number of tests for `wpull.pipeline` check whether the peak work item number is a certain number. However, the items may finish early, and this can lead to test failures. I noticed this in particular when the system was under high load or when I throttled the CPU frequency.

Here's an example failure (paths redacted):

    ======================================================================
    FAIL: test_concurrency_step_down (wpull.pipeline.pipeline_test.TestPipeline)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File ".../wpull/testing/async.py", line 29, in wrapper
        loop=self.event_loop)
      File ".../lib/python3.5/asyncio/base_events.py", line 337, in run_until_complete
        return future.result()
      File ".../lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File ".../lib/python3.5/asyncio/tasks.py", line 239, in _step
        result = coro.send(None)
      File ".../lib/python3.5/asyncio/tasks.py", line 386, in wait_for
        return fut.result()
      File ".../lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File ".../lib/python3.5/asyncio/tasks.py", line 239, in _step
        result = coro.send(None)
      File ".../wpull/pipeline/pipeline_test.py", line 239, in test_concurrency_step_down
        yield from pipeline.process()
      File ".../wpull/pipeline/pipeline.py", line 272, in process
        yield from self._process_one_worker()
      File ".../wpull/pipeline/pipeline.py", line 294, in _process_one_worker
        task.result()
      File ".../lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File ".../lib/python3.5/asyncio/tasks.py", line 239, in _step
        result = coro.send(None)
      File ".../wpull/pipeline/pipeline.py", line 176, in process
        item = yield from self.process_one(_worker_id=worker_id)
      File ".../wpull/pipeline/pipeline.py", line 159, in process_one
        yield from task.process(item)
      File ".../wpull/pipeline/pipeline_test.py", line 77, in process
        self.callback()
      File ".../wpull/pipeline/pipeline_test.py", line 228, in task_callback
        self.assertEqual(10, task.peak_work)
    AssertionError: 10 != 8
    -------------------- >> begin captured logging << --------------------
    asyncio: DEBUG: Using selector: EpollSelector
    wpull.pipeline.pipeline: DEBUG: pipeline processing: [<wpull.pipeline.pipeline_test.MyItemTask object at 0x7fdb4108f4e0>]
    wpull.pipeline.pipeline: DEBUG: Creating worker
    wpull.pipeline.pipeline: DEBUG: Creating worker
    wpull.pipeline.pipeline: DEBUG: Creating worker
    wpull.pipeline.pipeline: DEBUG: Creating worker
    wpull.pipeline.pipeline: DEBUG: Creating worker
    wpull.pipeline.pipeline: DEBUG: Creating worker
    wpull.pipeline.pipeline: DEBUG: Creating worker
    wpull.pipeline.pipeline: DEBUG: Creating worker
    wpull.pipeline.pipeline: DEBUG: Creating worker
    wpull.pipeline.pipeline: DEBUG: Creating worker
    wpull.pipeline.pipeline: DEBUG: Worker process id=0
    wpull.pipeline.pipeline: DEBUG: worker 0 processing <function Producer._make_get_item_from_source.<locals>._get_item_from_source at 0x7fdb41d06158>
    wpull.pipeline.pipeline: DEBUG: Get item from source
    wpull.pipeline.pipeline: DEBUG: worker 0 got: <MyItem at 7fdb41266eb8 value 1>
    wpull.pipeline.pipeline: DEBUG: Worker id 0 Processing item <MyItem at 7fdb41266eb8 value 1>
    wpull.pipeline.pipeline: DEBUG: Worker 0 processing item <MyItem at 7fdb41266eb8 value 1>, task <wpull.pipeline.pipeline_test.MyItemTask object at 0x7fdb4108f4e0>
    wpull.pipeline.pipeline: DEBUG: Worker process id=1
    wpull.pipeline.pipeline: DEBUG: Worker process id=2
    wpull.pipeline.pipeline: DEBUG: Worker process id=3
    wpull.pipeline.pipeline: DEBUG: Worker process id=4
    wpull.pipeline.pipeline: DEBUG: Worker process id=5
    wpull.pipeline.pipeline: DEBUG: Worker process id=6
    wpull.pipeline.pipeline: DEBUG: Worker process id=7
    wpull.pipeline.pipeline: DEBUG: Worker process id=8
    wpull.pipeline.pipeline: DEBUG: Worker process id=9
    wpull.pipeline.pipeline: DEBUG: worker 1 processing <function Producer._make_get_item_from_source.<locals>._get_item_from_source at 0x7fdb412229d8>
    wpull.pipeline.pipeline: DEBUG: Get item from source
    wpull.pipeline.pipeline: DEBUG: worker 1 got: <MyItem at 7fdb41266a20 value 2>
    wpull.pipeline.pipeline: DEBUG: Worker id 1 Processing item <MyItem at 7fdb41266a20 value 2>
    wpull.pipeline.pipeline: DEBUG: Worker 1 processing item <MyItem at 7fdb41266a20 value 2>, task <wpull.pipeline.pipeline_test.MyItemTask object at 0x7fdb4108f4e0>
    wpull.pipeline.pipeline: DEBUG: worker 2 processing <function Producer._make_get_item_from_source.<locals>._get_item_from_source at 0x7fdb41222ea0>
    wpull.pipeline.pipeline: DEBUG: Get item from source
    wpull.pipeline.pipeline: DEBUG: worker 2 got: <MyItem at 7fdb41266978 value 3>
    wpull.pipeline.pipeline: DEBUG: Worker id 2 Processing item <MyItem at 7fdb41266978 value 3>
    wpull.pipeline.pipeline: DEBUG: Worker 2 processing item <MyItem at 7fdb41266978 value 3>, task <wpull.pipeline.pipeline_test.MyItemTask object at 0x7fdb4108f4e0>
    wpull.pipeline.pipeline: DEBUG: worker 3 processing <function Producer._make_get_item_from_source.<locals>._get_item_from_source at 0x7fdb41222510>
    wpull.pipeline.pipeline: DEBUG: Get item from source
    wpull.pipeline.pipeline: DEBUG: worker 3 got: <MyItem at 7fdb41266940 value 4>
    wpull.pipeline.pipeline: DEBUG: Worker id 3 Processing item <MyItem at 7fdb41266940 value 4>
    wpull.pipeline.pipeline: DEBUG: Worker 3 processing item <MyItem at 7fdb41266940 value 4>, task <wpull.pipeline.pipeline_test.MyItemTask object at 0x7fdb4108f4e0>
    wpull.pipeline.pipeline: DEBUG: Worker id 1 Processed item <MyItem at 7fdb41266a20 value 2>
    wpull.pipeline.pipeline: DEBUG: worker 1 processing <function Producer._make_get_item_from_source.<locals>._get_item_from_source at 0x7fdb41222620>
    wpull.pipeline.pipeline: DEBUG: Get item from source
    wpull.pipeline.pipeline: DEBUG: worker 1 got: <MyItem at 7fdb41266908 value 5>
    wpull.pipeline.pipeline: DEBUG: Worker id 1 Processing item <MyItem at 7fdb41266908 value 5>
    wpull.pipeline.pipeline: DEBUG: Worker 1 processing item <MyItem at 7fdb41266908 value 5>, task <wpull.pipeline.pipeline_test.MyItemTask object at 0x7fdb4108f4e0>
    wpull.pipeline.pipeline: DEBUG: worker 5 processing <function Producer._make_get_item_from_source.<locals>._get_item_from_source at 0x7fdb41222730>
    wpull.pipeline.pipeline: DEBUG: Get item from source
    wpull.pipeline.pipeline: DEBUG: worker 5 got: <MyItem at 7fdb412668d0 value 6>
    wpull.pipeline.pipeline: DEBUG: Worker id 5 Processing item <MyItem at 7fdb412668d0 value 6>
    wpull.pipeline.pipeline: DEBUG: Worker 5 processing item <MyItem at 7fdb412668d0 value 6>, task <wpull.pipeline.pipeline_test.MyItemTask object at 0x7fdb4108f4e0>
    wpull.pipeline.pipeline: DEBUG: Worker id 3 Processed item <MyItem at 7fdb41266940 value 4>
    wpull.pipeline.pipeline: DEBUG: worker 6 processing <function Producer._make_get_item_from_source.<locals>._get_item_from_source at 0x7fdb41222488>
    wpull.pipeline.pipeline: DEBUG: Get item from source
    wpull.pipeline.pipeline: DEBUG: worker 6 got: <MyItem at 7fdb41266860 value 7>
    wpull.pipeline.pipeline: DEBUG: Worker id 6 Processing item <MyItem at 7fdb41266860 value 7>
    wpull.pipeline.pipeline: DEBUG: Worker 6 processing item <MyItem at 7fdb41266860 value 7>, task <wpull.pipeline.pipeline_test.MyItemTask object at 0x7fdb4108f4e0>
    wpull.pipeline.pipeline: DEBUG: worker 7 processing <function Producer._make_get_item_from_source.<locals>._get_item_from_source at 0x7fdb41222840>
    wpull.pipeline.pipeline: DEBUG: Get item from source
    wpull.pipeline.pipeline: DEBUG: worker 7 got: <MyItem at 7fdb41266828 value 8>
    wpull.pipeline.pipeline: DEBUG: Worker id 7 Processing item <MyItem at 7fdb41266828 value 8>
    wpull.pipeline.pipeline: DEBUG: Worker 7 processing item <MyItem at 7fdb41266828 value 8>, task <wpull.pipeline.pipeline_test.MyItemTask object at 0x7fdb4108f4e0>
    wpull.pipeline.pipeline: DEBUG: Worker id 5 Processed item <MyItem at 7fdb412668d0 value 6>
    wpull.pipeline.pipeline: DEBUG: worker 5 processing <function Producer._make_get_item_from_source.<locals>._get_item_from_source at 0x7fdb41222598>
    wpull.pipeline.pipeline: DEBUG: Get item from source
    wpull.pipeline.pipeline: DEBUG: worker 5 got: <MyItem at 7fdb41266748 value 9>
    wpull.pipeline.pipeline: DEBUG: Worker id 5 Processing item <MyItem at 7fdb41266748 value 9>
    wpull.pipeline.pipeline: DEBUG: Worker 5 processing item <MyItem at 7fdb41266748 value 9>, task <wpull.pipeline.pipeline_test.MyItemTask object at 0x7fdb4108f4e0>
    wpull.pipeline.pipeline: DEBUG: worker 9 processing <function Producer._make_get_item_from_source.<locals>._get_item_from_source at 0x7fdb41222950>
    wpull.pipeline.pipeline: DEBUG: Get item from source
    wpull.pipeline.pipeline: DEBUG: worker 9 got: <MyItem at 7fdb41266710 value 10>
    wpull.pipeline.pipeline: DEBUG: Worker id 9 Processing item <MyItem at 7fdb41266710 value 10>
    wpull.pipeline.pipeline: DEBUG: Worker 9 processing item <MyItem at 7fdb41266710 value 10>, task <wpull.pipeline.pipeline_test.MyItemTask object at 0x7fdb4108f4e0>
    wpull.pipeline.pipeline: DEBUG: Worker id 7 Processed item <MyItem at 7fdb41266828 value 8>
    wpull.pipeline.pipeline: DEBUG: worker 4 processing <function Producer._make_get_item_from_source.<locals>._get_item_from_source at 0x7fdb412228c8>
    wpull.pipeline.pipeline: DEBUG: Get item from source
    wpull.pipeline.pipeline: DEBUG: worker 4 got: <MyItem at 7fdb41266588 value 11>
    wpull.pipeline.pipeline: DEBUG: Worker id 4 Processing item <MyItem at 7fdb41266588 value 11>
    wpull.pipeline.pipeline: DEBUG: Worker 4 processing item <MyItem at 7fdb41266588 value 11>, task <wpull.pipeline.pipeline_test.MyItemTask object at 0x7fdb4108f4e0>
    wpull.pipeline.pipeline: DEBUG: worker 3 processing <function Producer._make_get_item_from_source.<locals>._get_item_from_source at 0x7fdb41222d90>
    wpull.pipeline.pipeline: DEBUG: Get item from source
    wpull.pipeline.pipeline: DEBUG: worker 3 got: <MyItem at 7fdb41266128 value 12>
    wpull.pipeline.pipeline: DEBUG: Worker id 3 Processing item <MyItem at 7fdb41266128 value 12>
    wpull.pipeline.pipeline: DEBUG: Worker 3 processing item <MyItem at 7fdb41266128 value 12>, task <wpull.pipeline.pipeline_test.MyItemTask object at 0x7fdb4108f4e0>
    wpull.pipeline.pipeline: DEBUG: Worker id 0 Processed item <MyItem at 7fdb41266eb8 value 1>
    wpull.pipeline.pipeline: DEBUG: Worker id 9 Processed item <MyItem at 7fdb41266710 value 10>
    wpull.pipeline.pipeline: DEBUG: worker 9 processing <function Producer._make_get_item_from_source.<locals>._get_item_from_source at 0x7fdb412229d8>
    wpull.pipeline.pipeline: DEBUG: Get item from source
    wpull.pipeline.pipeline: DEBUG: worker 9 got: <MyItem at 7fdb41266048 value 13>
    wpull.pipeline.pipeline: DEBUG: Worker id 9 Processing item <MyItem at 7fdb41266048 value 13>
    wpull.pipeline.pipeline: DEBUG: Worker 9 processing item <MyItem at 7fdb41266048 value 13>, task <wpull.pipeline.pipeline_test.MyItemTask object at 0x7fdb4108f4e0>
    wpull.pipeline.pipeline: DEBUG: worker 7 processing <function Producer._make_get_item_from_source.<locals>._get_item_from_source at 0x7fdb41222510>
    wpull.pipeline.pipeline: DEBUG: Get item from source
    wpull.pipeline.pipeline: DEBUG: worker 7 got: <MyItem at 7fdb41139860 value 14>
    wpull.pipeline.pipeline: DEBUG: Worker id 7 Processing item <MyItem at 7fdb41139860 value 14>
    wpull.pipeline.pipeline: DEBUG: Worker 7 processing item <MyItem at 7fdb41139860 value 14>, task <wpull.pipeline.pipeline_test.MyItemTask object at 0x7fdb4108f4e0>
    wpull.pipeline.pipeline: DEBUG: Worker id 3 Processed item <MyItem at 7fdb41266128 value 12>
    wpull.pipeline.pipeline: DEBUG: worker 0 processing <function Producer._make_get_item_from_source.<locals>._get_item_from_source at 0x7fdb41222730>
    wpull.pipeline.pipeline: DEBUG: Get item from source
    wpull.pipeline.pipeline: DEBUG: worker 0 got: <MyItem at 7fdb41139828 value 15>
    wpull.pipeline.pipeline: DEBUG: Worker id 0 Processing item <MyItem at 7fdb41139828 value 15>
    wpull.pipeline.pipeline: DEBUG: Worker 0 processing item <MyItem at 7fdb41139828 value 15>, task <wpull.pipeline.pipeline_test.MyItemTask object at 0x7fdb4108f4e0>
    wpull.pipeline.pipeline: DEBUG: Worker id 2 Processed item <MyItem at 7fdb41266978 value 3>
    wpull.pipeline.pipeline: DEBUG: worker 8 processing <function Producer._make_get_item_from_source.<locals>._get_item_from_source at 0x7fdb41222ea0>
    wpull.pipeline.pipeline: DEBUG: Get item from source
    wpull.pipeline.pipeline: DEBUG: worker 8 got: <MyItem at 7fdb411397f0 value 16>
    wpull.pipeline.pipeline: DEBUG: Worker id 8 Processing item <MyItem at 7fdb411397f0 value 16>
    wpull.pipeline.pipeline: DEBUG: Worker 8 processing item <MyItem at 7fdb411397f0 value 16>, task <wpull.pipeline.pipeline_test.MyItemTask object at 0x7fdb4108f4e0>
    wpull.pipeline.pipeline: DEBUG: Worker id 7 Processed item <MyItem at 7fdb41139860 value 14>
    wpull.pipeline.pipeline: DEBUG: worker 3 processing <function Producer._make_get_item_from_source.<locals>._get_item_from_source at 0x7fdb41222840>
    wpull.pipeline.pipeline: DEBUG: Get item from source
    wpull.pipeline.pipeline: DEBUG: worker 3 got: <MyItem at 7fdb411397b8 value 17>
    wpull.pipeline.pipeline: DEBUG: Worker id 3 Processing item <MyItem at 7fdb411397b8 value 17>
    wpull.pipeline.pipeline: DEBUG: Worker 3 processing item <MyItem at 7fdb411397b8 value 17>, task <wpull.pipeline.pipeline_test.MyItemTask object at 0x7fdb4108f4e0>
    wpull.pipeline.pipeline: DEBUG: Worker id 1 Processed item <MyItem at 7fdb41266908 value 5>
    wpull.pipeline.pipeline: DEBUG: worker 2 processing <function Producer._make_get_item_from_source.<locals>._get_item_from_source at 0x7fdb41222950>
    wpull.pipeline.pipeline: DEBUG: Get item from source
    wpull.pipeline.pipeline: DEBUG: worker 2 got: <MyItem at 7fdb41139780 value 18>
    wpull.pipeline.pipeline: DEBUG: Worker id 2 Processing item <MyItem at 7fdb41139780 value 18>
    wpull.pipeline.pipeline: DEBUG: Worker 2 processing item <MyItem at 7fdb41139780 value 18>, task <wpull.pipeline.pipeline_test.MyItemTask object at 0x7fdb4108f4e0>
    wpull.pipeline.pipeline: DEBUG: Worker id 8 Processed item <MyItem at 7fdb411397f0 value 16>
    wpull.pipeline.pipeline: DEBUG: worker 7 processing <function Producer._make_get_item_from_source.<locals>._get_item_from_source at 0x7fdb41222ea0>
    wpull.pipeline.pipeline: DEBUG: Get item from source
    wpull.pipeline.pipeline: DEBUG: worker 7 got: <MyItem at 7fdb41139748 value 19>
    wpull.pipeline.pipeline: DEBUG: Worker id 7 Processing item <MyItem at 7fdb41139748 value 19>
    wpull.pipeline.pipeline: DEBUG: Worker 7 processing item <MyItem at 7fdb41139748 value 19>, task <wpull.pipeline.pipeline_test.MyItemTask object at 0x7fdb4108f4e0>
    wpull.pipeline.pipeline: DEBUG: Worker id 6 Processed item <MyItem at 7fdb41266860 value 7>
    wpull.pipeline.pipeline: DEBUG: worker 1 processing <function Producer._make_get_item_from_source.<locals>._get_item_from_source at 0x7fdb41222d90>
    wpull.pipeline.pipeline: DEBUG: Get item from source
    wpull.pipeline.pipeline: DEBUG: worker 1 got: <MyItem at 7fdb41139710 value 20>
    wpull.pipeline.pipeline: DEBUG: Worker id 1 Processing item <MyItem at 7fdb41139710 value 20>
    wpull.pipeline.pipeline: DEBUG: Worker 1 processing item <MyItem at 7fdb41139710 value 20>, task <wpull.pipeline.pipeline_test.MyItemTask object at 0x7fdb4108f4e0>
    wpull.pipeline.pipeline_test: DEBUG: Set concurrency 1
    wpull.pipeline.pipeline: DEBUG: Put poison pill for less workers.
    wpull.pipeline.pipeline: DEBUG: Put poison pill for less workers.
    wpull.pipeline.pipeline: DEBUG: Put poison pill for less workers.
    wpull.pipeline.pipeline: DEBUG: Put poison pill for less workers.
    wpull.pipeline.pipeline: DEBUG: Put poison pill for less workers.
    wpull.pipeline.pipeline: DEBUG: Put poison pill for less workers.
    wpull.pipeline.pipeline: DEBUG: Put poison pill for less workers.
    wpull.pipeline.pipeline: DEBUG: Put poison pill for less workers.
    wpull.pipeline.pipeline: DEBUG: Put poison pill for less workers.
    wpull.pipeline.pipeline: DEBUG: 1 worker tasks completed
    wpull.pipeline.pipeline: DEBUG: Worker id 2 Processed item <MyItem at 7fdb41139780 value 18>
    wpull.pipeline.pipeline: DEBUG: worker 2 processing <function poison_pill_coro at 0x7fdb47205730>
    wpull.pipeline.pipeline: DEBUG: worker 2 got: <wpull.pipeline.pipeline._PoisonPill object at 0x7fdb472114e0>
    wpull.pipeline.pipeline: DEBUG: Worker quitting.
    wpull.pipeline.pipeline: DEBUG: worker 8 processing <function poison_pill_coro at 0x7fdb47205730>
    wpull.pipeline.pipeline: DEBUG: worker 8 got: <wpull.pipeline.pipeline._PoisonPill object at 0x7fdb472114e0>
    wpull.pipeline.pipeline: DEBUG: Worker quitting.
    wpull.pipeline.pipeline: DEBUG: worker 6 processing <function poison_pill_coro at 0x7fdb47205730>
    wpull.pipeline.pipeline: DEBUG: worker 6 got: <wpull.pipeline.pipeline._PoisonPill object at 0x7fdb472114e0>
    wpull.pipeline.pipeline: DEBUG: Worker quitting.
    wpull.pipeline.pipeline: DEBUG: Worker id 5 Processed item <MyItem at 7fdb41266748 value 9>
    wpull.pipeline.pipeline: DEBUG: worker 5 processing <function poison_pill_coro at 0x7fdb47205730>
    wpull.pipeline.pipeline: DEBUG: worker 5 got: <wpull.pipeline.pipeline._PoisonPill object at 0x7fdb472114e0>
    wpull.pipeline.pipeline: DEBUG: Worker quitting.
    wpull.pipeline.pipeline: DEBUG: Worker id 1 Processed item <MyItem at 7fdb41139710 value 20>
    wpull.pipeline.pipeline: DEBUG: worker 1 processing <function poison_pill_coro at 0x7fdb47205730>
    wpull.pipeline.pipeline: DEBUG: worker 1 got: <wpull.pipeline.pipeline._PoisonPill object at 0x7fdb472114e0>
    wpull.pipeline.pipeline: DEBUG: Worker quitting.
    asyncio: DEBUG: Close <_UnixSelectorEventLoop running=False closed=False debug=True>
    --------------------- >> end captured logging << ---------------------

The failures happen randomly on a number of tests, but I don't have a list available. I assume that all tests checking `peak_work` are affected.

The quick and dirty way to fix this would be to increase the sleep time within the items.

A better way to actually fix it would be to use a counter and let the items sleep until that counter reaches the expected peak number (with a timeout to prevent infinite loops when something is broken).

**Comment by JustAnotherArchivist** [comment]
Actually, even better would be to have the items sleep until all workers are busy. That might require changes to the pipeline itself though.
