### ISSUE TITLE
Error Running wpull

### ISSUE THREAD

**Issue by amryounis** [ArchiveTeam/wpull#486]
I receive the same error message from both Windows and Linux:

wpull --help
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Homer\miniconda3\envs\puller\Scripts\wpull.exe\__main__.py", line 4, in <module>
  File "C:\Users\Homer\miniconda3\envs\puller\Lib\site-packages\wpull\application\main.py", line 4, in <module>
    from wpull.application.builder import Builder
  File "C:\Users\Homer\miniconda3\envs\puller\Lib\site-packages\wpull\application\builder.py", line 8, in <module>
    from wpull.application.tasks.conversion import LinkConversionSetupTask, \
  File "C:\Users\Homer\miniconda3\envs\puller\Lib\site-packages\wpull\application\tasks\conversion.py", line 6, in <module>
    from wpull.pipeline.pipeline import ItemTask, ItemSource
  File "C:\Users\Homer\miniconda3\envs\puller\Lib\site-packages\wpull\pipeline\pipeline.py", line 21, in <module>
    class ItemTask(Generic[WorkItemT], metaclass=abc.ABCMeta):
  File "C:\Users\Homer\miniconda3\envs\puller\Lib\site-packages\wpull\pipeline\pipeline.py", line 23, in ItemTask
    @asyncio.coroutine
     ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'. Did you mean: 'coroutines'?

**Comment by TheTechRobo** [comment]
wpull requires Python 3.6. It does not support anything newer AFAIK (see #404).
